openjdk_version: openjdk-17-jdk
docker_package: docker-ce
docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo_url: https://download.docker.com/linux/ubuntu
docker_required_packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg
- software-properties-common
ebs_csi_role_arn: "arn:aws:iam::your arn:role/AmazonEKS_EBS_CSI_Driver_Role"
