openjdk_version: openjdk-17-jdk
jenkins_home: /home/ubuntu/jenkins_home
docker_package: docker-ce
docker_gpg_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo_url: https://download.docker.com/linux/ubuntu
docker_required_packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg
- software-properties-common